---
name: "pre-release"

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pre-release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Warsaw"

      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Generate FOO unique variable based on timestamp
        run: |
          cd dist
          sed -i "s/DEVDEV/prod-$(date +%Y-%m-%d_%H:%M)-${{ github.run_id }}/g" index.html
          zip -r eucentral.zip .

          echo FOO=$(date +%Y-%m-%d_%H_%M) >> $GITHUB_ENV

      - name: "Pre release"
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          tag_name: ${{ env.FOO }}
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
            dist/eucentral.zip

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "A new eucentral website release"
          to: work.opiela@gmail.com
          from: rafal.opiela@gmail.com
          body: |
            A new release of eucentral website has been published!

            Repository: ${{ github.repository }}
            Release: ${{ env.FOO }}
            Download it from: https://github.com/${{ github.repository }}/releases/download/${{ env.FOO }}/eucentral.zip
